# Generated by Django 3.1.4 on 2020-12-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.address')),
            ],
        ),
    ]
